oauth: add template helper base64encode
estuary/animated-carnival pull request #72
Opened 2022-09-21 13:24 UTC by mdibaiee

add a new helper `base64encode`, since sometimes we need to encode some headers

2022-09-21 19:00 UTC, jgraettinger requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/estuary/animated-carnival/72)* status: all files reviewed, 1 unresolved discussion (waiting on @jshearer, @mdibaiee, @psFried, @travjenkins, @willdonnelly, and @williamhbaker)

___
*[`supabase/functions/_shared/helpers.ts` line 20 at r1](https://reviewable.io/reviews/estuary/animated-carnival/72#-NCWPyUY62Nx1qX1J2E9:-NCWPyUY62Nx1qX1J2EA:b-4g1qug) ([raw file](https://github.com/estuary/animated-carnival/blob/d85726c0818008d083f56b5e59147bc814e8a77c/supabase/functions/_shared/helpers.ts#L20)):*
> ```XML
>     return btoa(s)
>   },
>   basicauth: function(user: string, pass: string) {
> ```

What's the use-case for this? It appears to base64 the user:password scheme?


<!-- Sent from Reviewable.io -->

2022-09-21 19:27 UTC, dyaffe commented
It's required by [source: notion](https://developers.notion.com/docs/authorization#exchanging-the-grant-for-an-access-token) for OAuth

2022-09-22 13:44 UTC, psFried approved these changes
LGTM as long as we're not trying to base64 encode any non-ascii data

2022-09-22 13:44 UTC, psFried commented on supabase/functions/_shared/helpers.ts
> +    return btoa(s)
IDK if it matters here, but against all reason the JS `btoa` function will error out on any non-ascii input characters. I'm guessing this is only used in scenarios where we're guaranteed ascii inputs, but worth a check.

2022-09-22 14:20 UTC, merged